### ISSUE TITLE
[question] Recover the task assignment after system restart

### ISSUE THREAD

**Issue by MinosPong** [Netflix/Fenzo#100]
Hi,
I am using the UniqueHostAttrConstraint to ensure tasks assigned to different host.
However, after the system restart. The constraint is not working. I believe this is due to the assignment history loss after restart.

So what will be the correct way to presisent the assignment history and recover it after system restart?

**Comment by spodila** [comment]
Fenzo maintains in memory state which needs to be rebuilt after a system restart. For example, upon system restart we first initialize task states from persistence (outside Fenzo, in our framework) and input the state into Fenzo by calling [TaskScheduler.getTaskAssigner().call(...)](http://netflix.github.io/Fenzo/fenzo-core/com/netflix/fenzo/TaskScheduler.html#getTaskAssigner--) for each task that was in the assigned state. After all running/assigned tasks have been input into Fenzo, the scheduling loop that calls TaskScheduler.scheduleOnce() is started, as explained in [here](https://github.com/Netflix/Fenzo/wiki/Scheduling-Tasks).

This way, Fenzo lets you use your favorite persistence and focuses purely on resource scheduling.

**Comment by spodila** [comment]
@MinosPong let me know if you need any further assistance on this topic.

**Comment by MinosPong** [comment]
Thank @spodila. Yes, your answer is helpful. I was using a old version of fenzo lib (0.8.2) which do not have ```
void setAssignedResources(AssignedResources assignedResources);
AssignedResources getAssignedResources();
```
Which make me confused how persistence the assigned resources. It looks good in the new version.

**Comment by spodila** [comment]
@MinosPong I am glad that worked for you.
I am curious as to what resources you are using for the AssignedResources in that call. We use that for a custom two level resource to represent assignable virtual network interfaces in EC2 VPC which can have multiple assignable IPs.

**Comment by spodila** [comment]
Feel free to reopen this or a new issue if you have more questions.
