### ISSUE TITLE
Fenzo on Openstack

### ISSUE THREAD

**Issue by gvenka008c** [Netflix/Fenzo#101]
@spodila Does Fenzo provides support on Openstack environment? Also how to setup and have it running?

**Comment by gvenka008c** [comment]
Can anyone provide the details on how to install and start using Fenzo on Openstack? Thanks.

**Comment by spodila** [comment]
There isn't a direct support for Openstack. However, what do you mean by support? 
Fenzo is a Java library that can be used by any Mesos framework. Fenzo itself isn't a process or a service by itself. It enables a service to do advanced scheduling of resources to tasks.

**Comment by gvenka008c** [comment]
@spodila Thanks. We have mesos/marathon cluster setup on Openstack. Can we use Fenzo for auto scale up/down on Openstack region?

**Comment by spodila** [comment]
@gvenka008c Fenzo is used in different frameworks that are built for specific purposes, some of them run concurrently with Marathon in the same Mesos cluster. You can get started writing your own framework with Fenzo by looking at [Sample Framework](http://netflix.github.io/Fenzo/fenzo-core/com/netflix/fenzo/samples/SampleFramework.html).

If you are planning to build a framework using Fenzo that will run along side other frameworks in the same Mesos cluster, note that autoscaling is triggered from the view of the framework using Fenzo. So, although scale up requests generated from Fenzo will work with no issues, scale down requests will need additional care when working in a multi-framework environment. It is not sufficient for one framework to decide to scale down an agent, in case that agent is running tasks from other frameworks.

**Comment by gvenka008c** [comment]
@spodila Thanks. We are not planning to build any framework. Can we use Fenzo integrated with existing framework which is marathon? Currently we use marathon to schedule all our jobs? How does marathon fenzo work together?

**Comment by spodila** [comment]
Integrating Fenzo with Marathon would imply that Marathon would use Fenzo for task placement. I am not aware of such integration at this time. You will have to ask Marathon to do this. I am glad to help such a discussion. Let me know how I can help.

**Comment by spodila** [comment]
Feel free to reopen this or a new issue if you have further questions.
