### ISSUE TITLE
advise on how to loop/tick fenzo 

### ISSUE THREAD

**Issue by senior7515** [Netflix/Fenzo#126]
Generally there are a couple of options:

1) ` new Thread().run() `
2)  with every mesos offer, enqueue and deuque 
3)  w/ timers - i.e.: actors - like the flink scheduler, or hierarchical timer wheel - for frequent timers. 

When developing a large framework - i.e.: relatively involved, where mesos is a small part - based on what you guys built at netflix, is there anything that works particularly well ? 

The downside of (1) is using thread.sleep() which is blocking. 

The downside of (2) is that given the async nature of fullfilling offers, it will probably not work for short expiration tasks. 

The downside of (3) is that you commit to their threading model - i.e.: actors, or callbacks for the time wheel approach which seem ok.  

Also this is more of a mailing list discussion, but couldn't find any, so I thought of issues as a way to record some fenzo wisdom. :)  - maybe it can turn into docs PR later !

**Comment by senior7515** [comment]
actually premature. you'd run it on the leader election callback as a blocking thread.

**Comment by spodila** [comment]
Although we have created fenzo@googlegroups.com so far most questions have been discussed via github issues here. Feel free to use either.

In our system, upon leader election, a scheduling service object is activated. In your similar service, you'd interact with Fenzo in one of two possible ways:

1. When using TaskScheduler to interact with Fenzo, you'd maintain a scheduling loop that calls TaskScheduler.scheduleOnce() repeatedly, even if you have no new offers from Mesos. This allows the "bookkeeping" stuff to be run inside Fenzo routinely, including rejecting any old unused offers, triggering autoscaling of the cluster, etc. For example, 
``` java
new ScheduledThreadPoolExecutor(1).scheduleWithFixedDelay(...)
```
can call the scheduling loop with a fixed delay between consecutive iterations. 

Or,

2. When using the (relatively) new TaskSchedulingService in Fenzo, you provide the scheduling iteration minimum and maximum delays between consecutive iterations, and Fenzo maintains the scheduling loop, giving you callbacks for launching tasks and releasing expired offers. See details on the delay controls [here](http://netflix.github.io/Fenzo/fenzo-core/com/netflix/fenzo/TaskSchedulingService.Builder.html)

I hope that helps.
