### ISSUE TITLE
how to handle remove offers from TaskSchedulingService in response to offerRescinded event from mesos master

### ISSUE THREAD

**Issue by blackgold** [Netflix/Fenzo#130]

**Comment by spodila** [comment]
You can do that with [TaskScheduler.expireLease()](http://netflix.github.io/Fenzo/fenzo-core/com/netflix/fenzo/TaskScheduler.html#expireLease-java.lang.String-) method, which takes the offer Id given by Mesos. Also see two other variants: [expireAllLeasesByVMId()](http://netflix.github.io/Fenzo/fenzo-core/com/netflix/fenzo/TaskScheduler.html#expireAllLeasesByVMId-java.lang.String-) which takes the agentId parameter and [expireAllLeases()](http://netflix.github.io/Fenzo/fenzo-core/com/netflix/fenzo/TaskScheduler.html#expireAllLeases-java.lang.String-) which takes the hostname parameter.

**Comment by devendra-nvidia** [comment]
that was it. Thank you

**Comment by spodila** [comment]
The previous response seems to answer your question, so closing this.
