### ISSUE TITLE
contributor agreement. 

### ISSUE THREAD

**Issue by senior7515** [Netflix/Fenzo#131]
is the indiv contributor agreement different than corporate contributor agreement. 

also, is it as easy as just signing your PR via git -s 

is it just the normal apache 2 ..i.e.: https://www.apache.org/licenses/cla-corporate.txt ?

**Comment by spodila** [comment]
It is the apache 2 license, as referenced in the top comments section in each source file.

**Comment by senior7515** [comment]
got ya, i was asked if the copyright is always netflix or the contributing company. 

i.e.:

```
/* Copyright 2015 Netflix, Inc.
*/
```
vs
 ```
/* Copyright 2015 Akamai Technologies, Inc.
*/
```

If the former, then we have to do sign a rights etc and give it to the project which is why I asked for a CLA - similar to Google's CLA. 

if the latter, then we're good. thanks!

**Comment by spodila** [comment]
It is the former. 
Here is an example contributors document from another NetflixOSS project, [Hystrix](https://github.com/Netflix/Hystrix/blob/master/CONTRIBUTING.md)

I can include a similar one for Fenzo soon.
Does that help?

**Comment by senior7515** [comment]
Yup. Perfect. Thanks.

**Comment by senior7515** [comment]
hi @spodila so aparently we need something like this: 

https://cla.developers.google.com/about/google-corporate

we are happy to hand over, but there has to be an official handoff of copyright.

**Comment by spodila** [comment]
I am checking on this, will get back to you shortly.

**Comment by senior7515** [comment]
I have an idea, what if there is a folder or smth like that, and I just push a commit w/ the template from apache2 site? kind of weird, but good enough... as a thought. maybe there is a branch called /legal or smth like that.

**Comment by spodila** [comment]
I am told that your idea seems good for us. Please go ahead and include the template along with your commit.
Thank you.
