### ISSUE TITLE
 Execution failed for task ':fenzo-core:compileJava'.> 无效的源发行版: 1.8

### ISSUE THREAD

**Issue by 215107821** [Netflix/Fenzo#152]
11:30:45.916 [ERROR] [org.gradle.BuildExceptionReporter]
11:30:45.917 [ERROR] [org.gradle.BuildExceptionReporter] FAILURE: Build failed with an exception.
11:30:45.918 [ERROR] [org.gradle.BuildExceptionReporter]
11:30:45.918 [ERROR] [org.gradle.BuildExceptionReporter] * What went wrong:
11:30:45.918 [ERROR] [org.gradle.BuildExceptionReporter] Execution failed for task ':fenzo-core:compileJava'.
11:30:45.918 [ERROR] [org.gradle.BuildExceptionReporter] > 无效的源发行版: 1.8
11:30:45.919 [ERROR] [org.gradle.BuildExceptionReporter]
11:30:45.919 [ERROR] [org.gradle.BuildExceptionReporter] * Exception is:
11:30:45.920 [ERROR] [org.gradle.BuildExceptionReporter] org.gradle.api.tasks.TaskExecutionException: Execution failed f
or task ':fenzo-core:compileJava'.
11:30:45.921 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.ExecuteAction
sTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
11:30:45.921 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.ExecuteAction
sTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
11:30:45.921 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.PostExecution
AnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
11:30:45.921 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.SkipUpToDateT
askExecuter.execute(SkipUpToDateTaskExecuter.java:68)
11:30:45.921 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.ValidatingTas
kExecuter.execute(ValidatingTaskExecuter.java:58)
11:30:45.921 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.SkipEmptySour
ceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)

**Comment by spodila** [comment]
Fenzo builds for me. Also, the automated builds on this site are passing. Could you elaborate on how you got this error?

**Comment by spodila** [comment]
Closing due to no response. Let us know if you still any trouble.
