### ISSUE TITLE
DisableVM does not remember hosts

### ISSUE THREAD

**Issue by zonybob** [Netflix/Fenzo#178]
The explanation for TaskScheduler:disableVM indicates that it will remember the "disabled" state if the VM is not yet known by Fenzo.
http://netflix.github.io/Fenzo/fenzo-core/com/netflix/fenzo/TaskScheduler.html#disableVM-java.lang.String-long-

In my testing, I was not observing this to be working. If I disable a VM before offers are received from it, it still comes up in an enabled state.

**Comment by corindwyer** [comment]
You are correct. The AssignableVM is only disabled if it exists. I will update the javadoc to reflect this. Also, Titus is not using this functionality as we have found it is better to have a hard constraint that disables placement on particular hosts.

**Comment by zonybob** [comment]
Thanks for the response. We will try to move forward with hard constraints instead.
