### ISSUE TITLE
Auto scaling

### ISSUE THREAD

**Issue by maselvaraj** [Netflix/Fenzo#43]
Read about Fenzo in netflix blog. Auto scaling concept sounds interesting. I'm yet to try my hands on Fenzo. Can you please let me know context of auto scaling here? Is it like Fenzo will shutdown/bring up VMs based on the demand ? 

Thanks in advance,
Mani

**Comment by spodila** [comment]
Fenzo provides the logic/smarts to shutdown or bring up VMs based on demand. It provides a callback mechanism. You provide the implementation of the callback inside which you will use your preferred way to bring up the VMs or terminate them. See [here](http://netflix.github.io/Fenzo/fenzo-core/com/netflix/fenzo/TaskScheduler.html#setAutoscalerCallback-com.netflix.fenzo.functions.Action1-).

**Comment by maselvaraj** [comment]
Thanks @spodila ! Is there a DL where I can reach out if I have any questions ?

**Comment by captify-akraievoy** [comment]
I would still maybe add a bit of clarification to the front page, because 
> [it can autoscale the execution hosts cluster based on demand for resources](https://github.com/Netflix/Fenzo/blame/master/README.md#L17)

is misleading, I was trying to find your AWS EC2 autoscaling engine for something like 30 minutes to no avail. Maybe 

> it's possible to implement cluster autoscaling via provided action callback

would be much more precise?
