### ISSUE TITLE
If a VMLease returns null for its attributes, fenzo silently fails to assign tasks

### ISSUE THREAD

**Issue by dgrnbrg** [Netflix/Fenzo#61]
It'd be great if the (I assume) NPE was logged or bubbled up somewhere.

**Comment by spodila** [comment]
There must be something else going on here. Null attributes by themselves don't cause trouble. For example, see null attribute usage in unit test [here](https://github.com/Netflix/Fenzo/blob/master/fenzo-core/src/test/java/com/netflix/fenzo/BasicSchedulerTests.java#L263).
Do you have any constraints defined in this setup?

**Comment by dgrnbrg** [comment]
I think that the issue is this line: https://github.com/Netflix/Fenzo/blob/master/fenzo-core/src/main/java/com/netflix/fenzo/TaskScheduler.java#L541

Essentially, I expect that Fenzo will report me errors so that I can handle/debug them, but if it's not an expected type of error, then I have to know to check the log.

What do you think about always rethrowing those errors?

**Comment by spodila** [comment]
Fenzo 0.8.5 now has support for returning exceptions caught during calls to user provided plugins and aborting the scheduler run. See details here: [http://netflix.github.io/Fenzo/fenzo-core/com/netflix/fenzo/TaskScheduler.html#scheduleOnce-java.util.List-java.util.List-](http://netflix.github.io/Fenzo/fenzo-core/com/netflix/fenzo/TaskScheduler.html#scheduleOnce-java.util.List-java.util.List-)

**Comment by dgrnbrg** [comment]
Thank you!
