### ISSUE TITLE
com.netflix.fenzo.TaskScheduler do not cleanup ThreadPool created by ExecutorService

### ISSUE THREAD

**Issue by MinosPong** [Netflix/Fenzo#70]
Hi,
I find that my application failed to shutdown gracefully after using TaskScheduler. After code trace, seems the ExecutorService is not shutdown (and has no way to do it). Can we have shutdown call in TaskScheduler to clear up threadpool?

**Comment by spodila** [comment]
This is now available via the new shutdown() method in TaskScheduler in fenzo-core 0.8.5. 
See [this](https://github.com/Netflix/Fenzo/blob/master/fenzo-core/src/test/java/com/netflix/fenzo/TestLotsOfTasks.java#L128) for sample usage.

**Comment by MinosPong** [comment]
Very nice. Thank you for the quick update!!!
