### ISSUE TITLE
Reject Leases on single hosts to avoid fragmentation

### ISSUE THREAD

**Issue by jamiethermo** [Netflix/Fenzo#87]
In `com.netflix.fenzo.AssignableVMs#removeLimitedLeases` there is this comment:
`// randomize the list so we don't always reject leases of the same VM before hitting the reject limit`
Don't we want to free up large chunks of contiguous space on a single VM, rather than fragmenting space across lots of machines?
See @spodila comment on #50

**Comment by spodila** [comment]
@jamiethermo This is now fixed and available in 0.11.7
