### ISSUE TITLE
TaskRequest should support wait queue expiration

### ISSUE THREAD

**Issue by q10** [Netflix/Fenzo#88]
When a TaskRequest is submitted to a Fenzo scheduler (`scheduler.scheduleOnce()`), it stays in the scheduler's internal queue until a resource offer comes in that fits its requirements.  However, it may be the case that no such offered resource will ever satisfy it, and so we would like for the task to be auto-removed from the internal queue after sitting there for a specified amount of time, instead of bad TaskRequests filling up the queue forever.  To support this, the following things would be needed:
1. specifying the queue wait timeout in the SchedulerBuilder `SchedulerBuilder.withQueueWaitTimeout(1000)`, where 1000 is seconds
2. ability to add a callback in either the Scheduler or SchedulerBuilder for TaskRequest removal-from-queue events, i.e. `SchedulerBuilder.withRemovedFromQueueCallback(Action1<TaskRequest>)` or `scheduler.setRemovedFromQueueCallback(Action1<TaskRequest>)`, 
3. the TaskRequest interface should specify a "int waitTimeout()" method that the scheduler can access to figure out of the task request has been waiting too long to be assigned.

**Comment by spodila** [comment]
Fenzo does not store task requests internally, it only stores the leases (aka, offers). There are already several ways to ensure the leases are expired timely. 

Or, are you suggesting that you'd like to have a queuing mechanism in Fenzo?

**Comment by q10** [comment]
I have a framework with Fenzo running in a loop on another thread (this is based on the example framework code provided in Fenzo repo).  What I noticed was that when I insert a TaskRequest and resources together in `scheduler.scheduleOnce()`, and the TaskRequest has a resource requirement that does not exist yet in the Mesos cluster, then I get a SchedulingResult where the VmAssignmentResult has no TaskAssignmentResultt  - this is expected.  However, after some time, when I register a new Mesos agent that offers resources matching the task's resource requirements, I notice that Fenzo will now output a TaskAssignmentResult that pairs that TaskRequest and the new resource together - this is good behavior.  I did not re-add the original task in via `scheduler.scheduleOnce()`, so I concluded that Fenzo must have some internal data structure that holds on to the TaskRequest that was sent in by the previous `scheduler.scheduleOnce()` call.  

What I would like is for Fenzo to not output a TaskAssignmentResult if the TaskRequest was sent in by a `scheduler.scheduleOnce()` call over N minutes ago, and for that TaskRequest to be kicked out from Fenzo if it is considered too old.  Is this currently possible

**Comment by spodila** [comment]
I was traveling with limited connectivity, so my response is delayed.

Although Fenzo is battle tested, the sample framework is not, it is provided as an example for how to use Fenzo in a framework. I would not recommend using the sample framework itself for any mission critical applications. Read the [comments provided in the sample](https://github.com/Netflix/Fenzo/blob/master/fenzo-core/src/main/java/com/netflix/fenzo/samples/SampleFramework.java#L220) for more details. 

Since Fenzo currently does not support queuing of tasks, you will have to support queuing in your framework. The sample framework is a simplistic example that maintains the collection of pending tasks to call Fenzo repeatedly.

**Comment by q10** [comment]
Ok, I see.  When I call scheduler.scheduleOnce() with a list of tasks, is it possible for me to bias the scheduling so that older-submitted tasks get prioritized first if they can be assigned to resources (i.e. if two task requests are given and score equally well in terms of fitness, but task request A is older than B, then choose A)?  Which FitnessCalculator or ConstraintEvaluator would be good for this?

**Comment by spodila** [comment]
Sure, Fenzo processes tasks in the order it receives via the List of task requests in the scheduleOnce() call. So, if you order the older tasks ahead in the list, they will be considered for resource assignment ahead of newer tasks. 

The fitness calculator is to choose an agent, for a given task, from multiple agents that can fit the task at the moment.

**Comment by spodila** [comment]
@q10 You may want to look at the recent introduced tasks queues in Fenzo. See details [here](https://github.com/Netflix/Fenzo/wiki/Task-Queues)

**Comment by q10** [comment]
Thanks

**Comment by spodila** [comment]
Feel free to reopen this or a new issue if you need further help.
