### ISSUE TITLE
Support for persistent volumes

### ISSUE THREAD

**Issue by timcharper** [Netflix/Fenzo#90]
Are there any plans to support multi-disk resources and persistent volume allocation / creation?

**Comment by spodila** [comment]
This has been discussed, but, hasn't been prioritized due to lack of immediate use cases within our environment. However, others with immediate use cases are looking at using Fenzo to still perform the constraints based resource assignment along with bin packing, and then perform the multi-step persistent volume handling with Mesos outside of Fenzo. 

Are there specific enhancements that would help you? PRs are welcome too.

**Comment by timcharper** [comment]
@spodila if there was a way to require that a task resident task be launched on a host with an already created persistentVolume, and the executor would provide the proper reservation command (IE includes the appropriate source information for the persistent volume) that would suffice for now.

**Comment by timcharper** [comment]
I'll look deeper at the source and see if it's easy to implement myself. You guys have done some fantastic work here so probably much easier to extend than to reimplement.

**Comment by spodila** [comment]
There is one minor change we can make to Fenzo that will allow you to do that. The VirtualMachineCurrentState object that is passed into ConstraintEvaluator currently does not provide the Mesos Offers represented on the agent. If we add that, then you can add a hard constraint to match the offer only if the created persistent volume exists in the offers. 

If that works for you, we can add that change.

Thanks for the kind words.

**Comment by timcharper** [comment]
Okay, thank you @spodila for your correspondence. After further thought, I think that there is perhaps more work required than I initially realized. I am wanting to deal exclusively with resident tasks (reserved resources). I think I could probably handle this outside of Fenzo (rather than accepting and launching a task... issue a reservation with a label for some pre-decided taskId, then wait for the reservation to be re-offered, intercept reservations, don't forward to Fenzo and launch).

In this case, Fenzo still helps decide where to launch things, but it doesn't seem like it helps with task reconciliation or error handling with the asynchronous reservations.

I think I might give dcos-commons a try, as it has implemented persistent volume allocation already and has library code for reconciliation, resource reservation, etc. It doesn't do the cool fitness evaluation that Fenzo does. I became convinced that I don't need it, and instead will have the user manually modify a `max-per-host` when scaling issues are encountered.

Thank you again for your collaboration. I think Fenzo would be an excellent choice if task residence wasn't so critical.
